{% set base_version = "1.0.0" %}
{% set version_postfix = "rc5" %}
{% set caffe_version = base_version + version_postfix %}

{% set cuda_version = "8.0" %}
{% set cudnn_version = "5.1" %}
{% set cuda_cudnn_version = cuda_version + "_" + cudnn_version %}
{% set caffe_cuda_cudnn_version = caffe_version + "_" + cuda_cudnn_version %}

{% set blas_variant = "openblas" %}

{% block recipe %}{% endblock %}

about:
  home: http://caffe.berkeleyvision.org/
  license: BSD 2-Clause
  summary: A deep learning framework made with expression, speed, and modularity in mind.

extra:
  recipe-url: https://github.com/loopbio/caffe-feedstock
  recipe-maintainers:
    - jakirkham
    - 183amir
    - sdvillal
