# Find our git repo: https://github.com/loopbio/caffe-feedstock

{% set base_version = "1.0.0" %}
{% set version_postfix = "rc5" %}
{% set version = base_version + version_postfix %}

{% set variant = "openblas" %}

package:
  name: caffe
  version: {{ version }}

source:
  fn: caffe_{{ version }}.tar.gz
  url: https://github.com/BVLC/caffe/archive/{{ version_postfix }}.tar.gz
  sha1: 7511c051a451f091fdf2cbd9b69be014fdc61f9b

build:
  number: 0
  skip: true  # [not linux]
  features:
    - blas_{{ variant }}
    - cuda80

requirements:
  build:
    - cmake
    - cython
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - boost 1.63.*
    - hdf5 1.8.17|1.8.17.*
    - gflags
    - glog
    - h5py
    - ipython
    - leveldb
    - lmdb
    - matplotlib
    - networkx
    - nose
    - numpy x.x
    - opencv 3.*
    - pandas
    - pillow
    - protobuf
    - python
    - python-dateutil
    - python-gflags
    - python-leveldb
    - pyyaml
    - scikit-image
    - scipy
    - six
    - snappy

    # Crazy bad things happening because of broken gtk2 management
    # Why does caffe try to load immediatly gtk2 and why is it linking to this oldie?
    # Why is caffe the only one actually having problems with icu?
    - icu=56.*

  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - boost 1.63.*
    - hdf5 1.8.17|1.8.17.*
    - gflags
    - glog
    - h5py
    - ipython
    - leveldb
    - lmdb
    - matplotlib
    - networkx
    - numpy x.x
    - opencv 3.*
    - pandas
    - pillow
    - protobuf
    - python
    - python-dateutil
    - python-gflags
    - python-leveldb
    - pyyaml
    - scikit-image
    - scipy
    - six
    - snappy

    # Crazy bad things happening because of broken gtk2 management
    # Why does caffe try to load immediatly gtk2 and why is it linking to this oldie?
    # Why is caffe the only one actually having problems with icu?
    - icu=56.*

test:
  requires:
    - cuda80-feature
  commands:
    # Test commands.
    - command -v "${PREFIX}/bin/caffe"
    - command -v "${PREFIX}/bin/classification"
    - command -v "${PREFIX}/bin/classify"
    - command -v "${PREFIX}/bin/compute_image_mean"
    - command -v "${PREFIX}/bin/convert_cifar_data"
    - command -v "${PREFIX}/bin/convert_imageset"
    - command -v "${PREFIX}/bin/convert_mnist_data"
    - command -v "${PREFIX}/bin/convert_mnist_siamese_data"
    - command -v "${PREFIX}/bin/detect"
    - command -v "${PREFIX}/bin/device_query"
    - command -v "${PREFIX}/bin/draw_net"
    - command -v "${PREFIX}/bin/extract_features"
    - command -v "${PREFIX}/bin/finetune_net"
    - command -v "${PREFIX}/bin/net_speed_benchmark"
    - command -v "${PREFIX}/bin/test_net"
    - command -v "${PREFIX}/bin/train_net"
    - command -v "${PREFIX}/bin/upgrade_net_proto_binary"
    - command -v "${PREFIX}/bin/upgrade_net_proto_text"
    - command -v "${PREFIX}/bin/upgrade_solver_proto_text"

    # Test includes.
    - test -d "${PREFIX}/include/caffe"

    # Test libraries.
    - test -f "${PREFIX}/lib/libcaffe.so"

  imports:
    - caffe

about:
  home: http://caffe.berkeleyvision.org/
  license: BSD 2-Clause
  summary: A deep learning framework made with expression, speed, and modularity in mind.

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - sdvillal (loopbio changes)
