channels:
  sources:
    - loopbio
    - conda-forge
    - defaults
  targets:
    - [loopbio, main]

github:
  user_or_org: 'loopbio'

docker:
  image: sdvillal/linux-anvil-cudnn

  # executable: nvidia-docker
  # See https://github.com/conda-forge/conda-smithy/pull/463
