{% extends 'base.yaml' %}

{% block recipe %}

package:
  name: caffe-cuda
  version: {{ caffe_cuda_cudnn_version }}

build:
  number: 0
  track_features:
    - caffe_{{ cuda_cudnn_version }}
  features:
    - cuda{{ cuda_version }}
    - cudnn{{ cudnn_version }}

requirements:
  run:
    - caffe

test:
  requires:
    - cuda-feature {{ cuda_version }}
    - cudnn-feature {{ cudnn_version }}
  imports:
    - caffe
  commands:
    - python -c "import caffe; caffe.set_mode_gpu(); caffe.set_device(0)"

{% endblock %}
