{% extends 'base.yaml' %}

{% block recipe %}

package:
  name: caffe-cuda-feature
  version: {{ caffe_cuda_version }}

build:
  number: 0
  track_features:
    - caffe_{{ cuda_version }}

{% endblock %}
